### PR TITLE
Converted default theme to Bootstrap 3

### PR DESCRIPTION
**Pull request by dirkluijk**
Hi,

Today I redesigned the default theme of jobberBase to Bootstrap 3. The main advantage is to make it easier to change the default theme and adapt it to your needs. Another benefit is that this theme will make jobberBase responsive. 
- Responsive layout
- Included most recent versions of
  - Bootstrap (3.1.1)
  - jQuery (2.1.1)
  - jQuery Validation (1.12.0)
- [Bower](http://bower.io) ready
- I used the default Bootstrap styles as much as possible. Very little custom CSS was added.
- It's easy to change to a [Bootswatch](http://bootswatch.com/) themes
- jQuery Validation messages are now localized (based on current environments locale)
- Changed directory structure, and simplified some templates

The theme is Bower ready, but I included all packages to keep installing jobberBase simple. Maybe it's a good idea to strip the included packages down to minimal size?

Before:

alt text - alt text 

After:

alt text - alt text 

TODO:
- [X] Test responsiveness of all pages on different devices
- [X] Find bugs

### CODE REVIEW

**Comment by dirkluijk** [comment]
I just improved the responsive part: on mobile devices a collapsing navbar with the search/add functionality was added, to replace the tabs navigation on tablet/desktop.

I forgot the 'Recommend to a friend' part, which is added now.

alt text - alt text

**Comment by dirkluijk** [comment]
I think this one is ready to be merged.

ping @filipcte

**Comment by filipcte** [comment]
This is fantastic, thank you for the contribution!
Please give me a few days to review the changes, before merging.

Thanks!

**Comment by dirkluijk** [comment]
No problem! Sorry btw for the large amounts of commits (still learning git). ;)

**Comment by filipcte** [comment]
Hello, could you close this pull request and send another one on the _develop_ branch, please? 
Thanks!

**Comment by dirkluijk** [comment]
No problem, will do. ;)

**Pull request closed without merging**
